### PR TITLE
Update Sim_EX1_178.cs

### PR DESCRIPTION
**Pull request by D-Nice**
Fixed the choices for "Ancient of War" to correspond to the correct actions, making the taunt choice likelier, which is more favourable in most cases, when playing a control deck.

### CODE REVIEW

**Comment by noHero123** [comment]
does the place of the cards change?
https://youtu.be/QRMo3YiIHZs?t=296
and
https://youtu.be/zAwrxlCTuu8?t=52

choice 1 stands for choocing the left card,
chois 2 = take the right one

**Comment by davidmann4** [comment]
good finding!
+1

**Comment by D-Nice** [comment]
Hmmm, on my HS version Uproot is on the left, and Rooted is on the right, hence the change here, as 1 is supposed to correspond to left, and 2 for right, the convention I've seen for most of the cards here. This merge request is required for the subsequent updates I made for Ancient of War to work properly, however, I guess we need to first figure out for whom uproot is left and for whom it is right.

**Comment by D-Nice** [comment]
The first video you linked was early 2014, and the second video was later 2014, so it may seem that in the early or beta version of HS they had Rooted (+5 Health Taunt) on the left, but now I'm quite sure it's on the right, as when I was playing Arena, it kept showing up on the right, yet the bot was clicking the left choice.

I personally don't own an Ancient of War in my collection, so if someone could test it out on practice, to see if it is in fact on the right side.

**Comment by yann510** [comment]
I do own an Ancient of War in my collection and I will test if the +5 is on the right or left, as soon as I have some free time.

**Comment by davidmann4** [comment]
gave it a shot - i played the card serveral times ( aborted the play with rightclick and played it again)

EU server - english locale - german client - newest version (TGT release) - windows 7

always resulting in this outcome:

**Comment by D-Nice** [comment]
Then this patch would be beneficial for anyone playing ancient of war, I tested it myself, I actually did also have a Ancient of War, and same results. This would indicate why it would always do Uproot when it was looking to do Rooted.

**Comment by D-Nice** [comment]
Nvm, this has already been added to the card. I'll close this request :). Thanks for also showing the tests to confirm David.

**Comment by davidmann4** [comment]
it was merged by hand? :-1:

**Pull request closed without merging**
